clear all, close all, clc
% The values in this script have been
% generated by PCSVA denoising,
% with appropriate modifications to 
% parameters
LW = 2.5;
LW2 = 8;
Mark = '*';
FS = 14;
%% N1 @ sigma = 0.05
N1 = 4:8;
SSIM = [93.4,94.12,94.22,94.12,93.85];
RMSE = [1.57,1.5,1.49,1.51,1.53];
figure,
xticks(N1)
xlabel('N_1')
yyaxis right
plot(N1,SSIM,LineWidth=LW)
hold on
plot(6,SSIM(3),LineWidth=LW2,Marker=Mark,Color='black')
yyaxis left 
plot(N1,RMSE,LineWidth=LW)
plot(6,RMSE(3),LineWidth=LW2,Marker=Mark,Color='black')

grid on
title('Tuning of N_1 at \sigma_{noise}= 0.05')
legend('RMSE','','SSIM','')
set(gca,'FontSize',FS,'fontWeight','bold')
%set(findall(gcf,'type','text'),'FontSize',FS,'fontWeight','bold')

%% N2 @ sigma = 0.10
N2 = 30:10:70;
SSIM = [88.59,89.23,89.47,89.55,89.57];
RMSE = [2.29,2.29,2.3,2.31,2.33];
figure,
xticks(N2)
xlabel('N_2')
yyaxis right
plot(N2,SSIM,LineWidth=LW)
hold on
plot(50,SSIM(3),LineWidth=LW2,Marker=Mark,Color='black')
yyaxis left 
plot(N2,RMSE,LineWidth=LW)
plot(50,RMSE(3),LineWidth=LW2,Marker=Mark,Color='black')

grid on
title('Tuning of N_2 at \sigma_{noise}= 0.10')
legend('RMSE','','SSIM','',Location='southeast')
set(gca,'FontSize',FS,'fontWeight','bold')
%set(findall(gcf,'type','text'),'FontSize',FS,'fontWeight','bold')

%% delta @ sigma = 0.15
delt = [0.01,0.05:0.05:0.2];
SSIM = [85.80,85.57,85.13,84.32,81.36];
RMSE = [2.89,2.87,2.85,2.86,2.93];
figure,
xticks(delt)
xlabel('\delta')
yyaxis right
plot(delt,SSIM,LineWidth=LW)
hold on
plot(0.1,SSIM(3),LineWidth=LW2,Marker=Mark,Color='black')
yyaxis left 
plot(delt,RMSE,LineWidth=LW)
plot(0.1,RMSE(3),LineWidth=LW2,Marker="*",Color='black')

grid on
title('Tuning of \delta at \sigma_{noise}= 0.15')
legend('RMSE','','SSIM','')
set(gca,'FontSize',FS,'fontWeight','bold')
%set(findall(gcf,'type','text'),'FontSize',FS,'fontWeight','bold')

%% c @ sigma = 0.05
c = 2.6:0.1:3;
SSIM = [94.18,94.20,94.22,94.22,94.23];
RMSE = [1.49,1.49,1.49,1.5,1.5];
figure,
xticks(c)
xlabel('c')
yyaxis right
plot(c,SSIM,LineWidth=LW)
hold on
plot(2.8,SSIM(3),LineWidth=LW2,Marker=Mark,Color='black')
yyaxis left 
plot(c,RMSE,LineWidth=LW)
plot(2.8,RMSE(3),LineWidth=LW2,Marker=Mark,Color='black')

grid on
title('Tuning of c at \sigma_{noise}= 0.05')
legend('RMSE','','SSIM','',Location='southeast')
set(gca,'FontSize',FS,'fontWeight','bold')
%set(findall(gcf,'type','text'),'FontSize',FS,'fontWeight','bold')
